//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_Testing3_NET_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDH { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> UserID { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string TrangThai { get; set; }
    }
}
