//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_Testing3_NET_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public decimal Gia { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<int> SoLuongKho { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public string MaLoai { get; set; }
        public string Hinh { get; set; }
        public string TinhNang { get; set; }
        public string MoTa { get; set; }
    }
}
